/*
 * Author: Aurelio Colosimo, 2016
 * Released under MIT-Expat License.
 */

/* Tool to compute bit-reversal for FFT pre-ordering
 *
 * Usage: psdr-bitrev N output.h output.c
 *        N: number of elements
 *        nbits: number of bits of each real/imaginary value
 *        output.h: filename for generated .h
 *        output.c: filename for generated .c
 */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libgen.h>

#define EXE "psdr-bitreverse"

#define COMMON_HEADER \
    "/*\n * File %s\n * Automatically generated by " EXE " tool\n" \
    " * Command line:"

int main(int argc, char** argv)
{
	unsigned N, nbits, i, k, v, i1;
	FILE *fh = NULL, *fc = NULL;
	char *fcname;

	if (argc < 3) {
		printf("\n" EXE " - Tool to compute bit-reversal for FFT "
		    "pre-ordering\n\n");
		printf("Usage: " EXE " N output.h [output.c]\n");
		printf("\tN: number of elements\n");
		printf("\toutput.h: path to generated .h\n");
		printf("\toutput.c (optional): path to generated .c; if not provided, "
		    "computed from output.h\n");
		printf("\n");
		return 1;
	}

	N = strtoul(argv[1], NULL, 10);
	if (!N) {
		printf("Invalid N parameter: %s\n", argv[1]);
		return 1;
	}

	fh = fopen(argv[2], "w");
	if (!fh) {
		printf("Unable to open %s in write mode.\n", argv[2]);
		return 2;
	}

	if (argv[3])
		fcname = strdup(argv[3]);
	else {
		if (argv[2][strlen(argv[2]) - 1] != 'h') {
			printf("Invalid .h filename, cannot compute .c: %s\n", argv[2]);
			return 3;
		}
		fcname = strdup(argv[2]);
		fcname[strlen(argv[2]) - 1] = 'c';
	}
	fc = fopen(fcname, "w");
	if (!fc) {
		printf("Unable to open %s in write mode.\n", fcname);
		fclose(fh);
		return 4;
	}

	fprintf(fh, COMMON_HEADER, basename(argv[2]));
	fprintf(fc, COMMON_HEADER, basename(fcname));

	for (i = 0; i < argc; i++) {
		fprintf(fh, " %s", argv[i]);
		fprintf(fc, " %s", argv[i]);
	}

	fprintf(fh, "\n */\n\n");
	fprintf(fc, "\n */\n\n");

	fprintf(fc, "#include \"%s\"\n\n", basename(argv[2]));

	fprintf(fh, "extern const int bitrev%u[%u];\n", N, N);

	fclose(fh);

	fprintf(fc, "const int bitrev%u[%u] = {", N, N);

	nbits = log2(N);

	for (i = 0; i < N; i++) {
		i1 = i;
		v = 0;
		for (k = 0; k < nbits; k++) {
			v = v | ((i1 & 1) << (nbits - k - 1));
			i1 >>= 1;
		}
		if (i % 8 == 0)
			fprintf(fc, "\n\t");
		fprintf(fc, "%u, ", v);
	}

	fprintf(fc, "\n};\n");

	fclose(fc);

	free(fcname);

	return 0;
}
